# Use Debian as base image
FROM debian:bullseye


COPY ./tools/entrypoint.sh /usr/local/bin/

COPY ./tools/mariadb_dump/database_dump.sql /

RUN chmod +x /usr/local/bin/entrypoint.sh

# Install MariaDB server and client
RUN apt-get update && \
    apt-get install -y mariadb-server mariadb-client && \
    apt-get clean && \
    apt install -y vim 
    # && \
    # apt install -y vim 
    # rm -rf /var/lib/apt/lists/*
# Expose the MySQL default port
EXPOSE 3306

# Set the entrypoint to start the MariaDB service
ENTRYPOINT ["entrypoint.sh"]

# CMD ["sleep", "1098765678909876789876"]
CMD ["mysqld", "--bind-address=0.0.0.0"]
