FROM debian:bullseye

RUN apt update \
    && apt install -y php7.4 php7.4-fpm  \
    && apt install net-tools \
    && apt install -y systemctl \
    && apt-get install -y wget tar \
    && apt install -y iproute2 \
    && apt install -y inetutils-ping \
    && apt install -y bind9-utils \
    && apt install -y vim \
    && apt install telnet \
    && apt-get install -y mariadb-client \
    curl \
    bash \
    php \
    php-cgi \
    php-mysql \
    php-pdo \
    php-gd \
    php-cli \
    php-mbstring \
    php-redis \
    redis-server \
    htop
    # && wget -O /tmp/wordpress.tar.gz https://wordpress.org/latest.tar.gz \
    # && tar -xzvf /tmp/wordpress.tar.gz -C /var/www/html \
    # && chown -R www-data.www-data /var/www/html/wordpress \
    # && chmod -R 755 /var/www/html/wordpress

COPY ./conf/www.conf /etc/php/7.4/fpm/pool.d/

COPY ./conf/test.conf /etc/php/7.4/fpm/pool.d/

COPY ./tools/entrypoint.sh /usr/local/bin/

RUN chmod 777 /usr/local/bin/entrypoint.sh

EXPOSE 9000

RUN useradd -u 1000 test

# USER test

ENTRYPOINT ["entrypoint.sh"]

# CMD ["php-fpm7.4", "-F"]

# CMD ["sleep", "1000000000000000000000000000"]