FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y openssl \
    wget \
    prometheus \
    vim \
    systemd \
    net-tools \
    ufw

COPY prometheus.yml  /etc/prometheus/prometheus.yml 

EXPOSE 9090

CMD ["/usr/bin/prometheus"]
