FROM debian:bullseye

RUN apt-get update && apt-get install -y php php-fpm php-mysqli \
    && apt install net-tools 

COPY adminer-4.8.1.php /

COPY entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/entrypoint.sh

COPY www.conf /etc/php/7.4/fpm/pool.d/

EXPOSE 9000


ENTRYPOINT ["entrypoint.sh"]

# Run php-fpm in foreground
CMD ["php-fpm7.4", "-F"]