FROM debian:bullseye


RUN apt update \
    && apt install -y nginx \
    && apt install -y vim \
    && apt install net-tools 

COPY my.conf /etc/nginx/conf.d/

COPY entrypoint.sh /usr/local/bin/

EXPOSE 80

ENTRYPOINT ["entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]