FROM debian:bullseye


RUN apt update \
    && apt install -y nginx \
    && apt install -y vim \
    && apt install net-tools 

COPY my.conf /etc/nginx/sites-available/

EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]