FROM debian:bullseye

COPY entrypoint.sh /usr/local/bin/

RUN apt update && \
    apt install -y php7.4 php7.4-fpm  \
    apt install net-tools \
    apt install -y syetemctl

COPY www.conf /etc/php/7.4/fpm/pool.d/

EXPOSE 9000

# Set the entrypoint
ENTRYPOINT ["entrypoint.sh"]


CMD ["php7.4-fpm ", "-F"]
