FROM debian:bullseye

RUN apt update \
    && apt install -y nginx \
    && apt install -y vim \
    && apt install net-tools \
    && apt-get install -y openssl \
    htop

COPY ./conf/my.conf /etc/nginx/conf.d/

COPY ./tools/entrypoint.sh /usr/local/bin/


# Generate self-signed SSL certificate and private key
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/certs/certificate.key -out /etc/ssl/certs/certificate.crt \
    -subj "/C=US/ST=State/L=City/O=Organization/CN=localhost"

# Copy the generated SSL certificate and private key to Nginx directory
RUN cp /etc/ssl/certs/certificate.crt  /etc/nginx/ssl.crt && \
    cp /etc/ssl/certs/certificate.key /etc/nginx/ssl.key

# EXPOSE 80

EXPOSE 443

# RUN useradd -u 1000 sukrit

# USER sukrit

ENTRYPOINT ["entrypoint.sh"]

# CMD ["sleep", "1000000000000000000000000000"]

CMD ["nginx", "-g", "daemon off;"]