# Use Debian as base image
FROM debian:bullseye

COPY entrypoint.sh /usr/local/bin/
# Install MariaDB server and client
RUN apt-get update && \
    apt-get install -y mariadb-server mariadb-client && \
    apt-get clean 
    # && \
    # apt install -y vim 
    # rm -rf /var/lib/apt/lists/*
# Expose the MySQL default port
EXPOSE 3306

# Set the entrypoint to start the MariaDB service
ENTRYPOINT ["entrypoint.sh"]


CMD ["mysqld"]
