FROM debian:bullseye

RUN apt-get update -y && apt-get install -y procps redis \
    && apt install -y vim \
    && apt install -y net-tools


COPY ./conf/redis.conf /usr/local/etc/redis/redis.conf

EXPOSE 6379


CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]