FROM debian:bullseye

RUN apt-get update -y && apt-get install -y procps redis \
    && apt install -y vim \
    && apt install -y net-tools

# COPY entrypoint.sh /usr/local/bin/

COPY redis.conf /usr/local/etc/redis/redis.conf

# RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 6379

# ENTRYPOINT ["entrypoint.sh"]

CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]